[tox]
envlist = py{37,38,39,310,311,312,313}-libcloud{30,31,32,33,34,35,36,37,38}
# https://libcloud.apache.org/about.html#supported-python-versions

[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[pytest]
addopts = -ra -v
testpaths = tests

[testenv]
description = Run pytest
passenv =
    DRIVER_KEY
    DRIVER_USER_ID
    DRIVER_PASSWORD
    DRIVER_TOKEN
deps =
    py{37,38,39,310,311}-libcloud30: apache-libcloud>=3.0.0,<3.1.0
    py{37,38,39,310,311}-libcloud31: apache-libcloud>=3.1.0,<3.2.0
    py{37,38,39,310,311}-libcloud32: apache-libcloud>=3.2.0,<3.3.0
    py{37,38,39,310,311,312,313}-libcloud33: apache-libcloud>=3.3.0,<3.4.0
    py{37,38,39,310,311,312,313}-libcloud34: apache-libcloud>=3.4.0,<3.5.0
    py{37,38,39,310,311,312,313}-libcloud35: apache-libcloud>=3.5.0,<3.6.0
    py{37,38,39,310,311,312,313}-libcloud36: apache-libcloud>=3.6.0,<3.7.0
    py{37,38,39,310,311,312,313}-libcloud37: apache-libcloud>=3.7.0,<3.8.0
    py{37,38,39,310,311,312,313}-libcloud38: apache-libcloud>=3.8.0,<3.9.0
    -rrequirements-tox.txt
commands =
    pytest -c tox.ini -ra -v {posargs}

[testenv:pre-commit]
description = Run all pre-commit hooks.
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files

[testenv:coverage]
description = Run pytest with coverage
passenv =
    DRIVER_KEY
    DRIVER_USER_ID
    DRIVER_PASSWORD
    DRIVER_TOKEN
deps =
    -rrequirements-tox.txt
commands =
    pytest --cov --cov-append --cov-report=term-missing --cov-fail-under 84 {posargs}
